# -*- coding: utf-8 -*-
"""NFL Data Engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109Y-lwjZE1TT_oNB2cBTZ8P4ZshoHWrr
"""

# ----------------------------------
#  Section 1: Data Ingestion
# ----------------------------------

import pandas as pd

# Load the CSV file from the URL
url = "https://nflsavant.com/pbp_data.php?year=2024"
df = pd.read_csv(url)

# Display total record count after ingestion
print("Total records after Data Ingestion:", len(df))


# ----------------------------------
#  Section 2: Data Processing
# ----------------------------------

# Remove records where IsPass and IsRush are both 0
df_filtered = df[~((df['IsPass'] == 0) & (df['IsRush'] == 0))]

# Remove records where PlayType is "SCRAMBLE"
df_filtered = df_filtered[df_filtered['PlayType'] != 'SCRAMBLE']

# Display total record count after processing
print("Total records after Data Processing:", len(df_filtered))


# ----------------------------------
# Section 3: Training and Testing Model
# ----------------------------------

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Define features and target
features = ['OffenseTeam', 'Down', 'ToGo', 'Quarter', 'Minute', 'YardLine']
target = 'IsPass'

# Drop missing values in selected columns
df_model = df_filtered[features + [target]].dropna()

X = df_model[features]
y = df_model[target]

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Preprocessing pipeline for categorical and numeric features
categorical_features = ['OffenseTeam']
numeric_features = ['Down', 'ToGo', 'Quarter', 'Minute', 'YardLine']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

# Create Random Forest pipeline
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Train the model
rf_pipeline.fit(X_train, y_train)

# Predict and evaluate accuracy
y_pred = rf_pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Random Forest Model Accuracy:", round(accuracy * 100, 2), "%")


# ----------------------------------
#  Section 4: Using the Model
# ----------------------------------

# Create prediction scenarios
scenarios = pd.DataFrame([
    {'OffenseTeam': 'MIN', 'Down': 3, 'ToGo': 10, 'Quarter': 2, 'Minute': 12, 'YardLine': 40},
    {'OffenseTeam': 'MIN', 'Down': 3, 'ToGo': 1, 'Quarter': 2, 'Minute': 12, 'YardLine': 40},
    {'OffenseTeam': 'MIN', 'Down': 3, 'ToGo': 4, 'Quarter': 2, 'Minute': 12, 'YardLine': 40}
])

# Predict probability of IsPass = 1
probabilities = rf_pipeline.predict_proba(scenarios)[:, 1]

# Attach probabilities to scenarios
scenarios['Probability_IsPass_1'] = probabilities

# Display results
print("\nPredictions for IsPass = 1:")
print(scenarios)